# ingredients_mapper.py

# 1) the map: raw → canonical
original_data = {
    # Beer
    "Lager": "Beer",
    "Ale": "Beer",
    "Guinness stout": "Beer",
    "Corona": "Beer",
    "Beer": "Beer",

    # Cider
    "Apple cider": "Cider",
    "Cider": "Cider",

    # Rum
    "Dark rum": "Rum",
    "Rum": "Rum",
    "Añejo rum": "Rum",
    "151 proof rum": "Rum",
    "Spiced Rum": "Rum",
    "Golden rum": "Rum",
    "Spiced rum": "Rum",


    # Flavored Rum
    "Coconut rum": "Flavored Rum",
    "Malibu rum": "Flavored Rum",
    "Bacardi Limon": "Flavored Rum",


    # Gin
    "Gin": "Gin",
    "Sloe gin": "Gin",

    # Flavored Vodka
    "Peach Vodka": "Flavored Vodka",
    "Vanilla vodka": "Flavored Vodka",
    "Absolut Citron": "Flavored Vodka",
    "Lemon vodka": "Flavored Vodka",
    "Maui": "Flavored Vodka",
    "Absolut Kurant": "Flavored Vodka",
    "Absolut Peppar": "Flavored Vodka",
    "Lime Vodka": "Flavored Vodka",
    "Raspberry Vodka": "Flavored Vodka",
    "Cranberry vodka": "Flavored Vodka",

    # White Rum
    "Light rum": "White rum",
    "White rum": "White rum",
    "White Rum": "White rum",

    # Vodka
    "Vodka": "Vodka",
    "Absolut Vodka": "Vodka",

    # Vermouth and Wines
    "Sweet Vermouth": "Sweet Vermouth",
    "Dry Vermouth": "Dry Vermouth",
    "Champagne": "Sparkling Wine",
    "Vermouth": "Vermouth",
    "Sherry": "Sherry",
    "Wine": "Wine",
    "Red wine": "Red Wine",
    "Cuvée": "Sparkling Wine",
    "Tawny Port": "Fortified Wine",
    "Dubonnet Rouge": "Sweet Vermouth",
    "Lillet Blanc": "Dry Vermouth",
    "CÃ´teau": "Wine",
    "Dubonnet": "Vermouth",
    "French vermouth": "Vermouth",
    "Lillet": "Dry Vermouth",
    "Port": "Fortified Wine",
    "Pouilly-Fuissé": "Wine",
    "Sake": "Sake",
    "Prosecco": "Sparkling Wine",

    # Whiskey
    "Scotch": "Whiskey",
    "Crown Royal": "Whiskey",
    "Jim Beam": "Whiskey",
    "Rye whiskey": "Whiskey",
    "Wild Turkey": "Whiskey",
    "Johnnie Walker": "Whiskey",
    "Jack Daniels":"Whiskey",
    "Irish Whiskey":"Whiskey",
    "Bourbon": "Whiskey",
    "Canadian whiskey": "Whiskey",
    "Blended whiskey": "Whiskey",
    "Whisky": "Whiskey",
    "Whiskey": "Whiskey",
    "Tennessee Whiskey": "Whiskey",
    "Irish whiskey": "Whiskey",

    # Brandy
    "Brandy": "Brandy",
    "Cognac": "Brandy",

    # Sugar Syrup
    "Grenadine": "Flavored Syrup",
    "Sugar": "Sweetener",
    "Sugar syrup": "Sweetener",
    "Brown sugar": "Sweetener",
    "Powdered Sugar": "Sweetener",
    "Chocolate syrup": "Flavored Syrup",
    "Passion fruit syrup": "Flavored Syrup",
    "Agave Syrup": "Flavored Syrup",
    "Honey":"Sweetener",
    "Sirup of roses": "Flavored Syrup",
    "Cinnamon syrup": "Flavored Syrup",
    "Currant syrup": "Flavored Syrup",
    "Blackcurrant cordial": "Flavored Syrup",
    "Blackcurrant squash": "Flavored Syrup",
    "Pineapple syrup": "Flavored Syrup",
    "Orgeat Syrup": "Flavored Syrup",
    "Mint Syrup": "Flavored Syrup",
    "Maple Syrup": "Flavored Syrup",
    "Fruit syrup": "Flavored Syrup",
    "Coconut syrup": "Flavored Syrup",
    "Cherry Grenadine": "Flavored Syrup",
    "Demajito": "Flavored Syrup",
    "Demerara Sugar": "Sweetener",
    "Elderflower cordial": "Flavored Syrup",
    "Falernum": "Flavored Syrup",
    "Gulab jal": "Flavored Syrup",
    "Habanero syrup": "Flavored Syrup",
    "Honey syrup": "Flavored Syrup",
    "Lime cordial": "Flavored Syrup",
    "Mocha syrup": "Flavored Syrup",
    "Cream of coconut": "Flavored Syrup",
    "Raspberry syrup": "Flavored Syrup",
    "Simple Syrup": "Sweetener",
    "caramel sauce": "Flavored Syrup",
    "demerara Sugar": "Sweetener",
    "Corn syrup": "Sweetener",
    "Glycerine": "Sweetener",

    # Flavored Whiskey
    "Southern Comfort": "Flavored Whiskey",
    "Yukon Jack": "Flavored Whiskey",
    "Hot Damn": "Flavored Whiskey",

    # Tequila
    "Tequila": "Tequila",
    "Gold tequila": "Tequila",
    "Mezcal": "Tequila",
    "Reposado tequila": "Tequila",
    "Tequila blanco": "Tequila",

    # Base Ingredients
    "Water": "Water",
    "Chocolate ice-cream": "Sweets",
    "Sour mix": "Sour mix",
    "Tea": "Tea",
    "Angelica root": "Herbs and Spices",
    "Orange juice": "Orange",
    "Berries": "Berries",
    "Apple juice": "Apple juice",
    "7-Up": "Lemon-Lime Soda",
    "Lemonade": "Lemonade",
    "Cantaloupe": "Cantaloupe",
    "Milk": "Milk",
    "Strawberries": "Strawberries",
    "Ice": "Ice",
    "Coca-Cola": "Cola",
    "Ginger beer": "Ginger Soda",
    "Soda water": "Soda water",
    "Lemon": "Lemon",
    "Grapefruit juice": "Uncommon Juices",
    "Peach nectar": "Uncommon Juices",
    "Sweet and sour": "Sweet and sour",
    "Lime juice": "Lime",
    "Cranberry Juice": "Cranberry Juice",
    "Lemon juice": "Lemon",
    "Ginger": "Herbs and Spices",
    "Light cream": "Cream",
    "Lime": "Lime",
    "Almond": "Nuts",
    "Apple": "Apple",
    "Carrot": "Carrot",
    "Grape soda": "Uncommon Soft-Drinks",
    "Mountain Dew": "Uncommon Soft-Drinks",
    "Iced tea": "Tea",
    "Sambuca": "Tea",
    "Black Sambuca": "Tea",
    "Vanilla ice-cream": "Sweets",
    "Banana": "Banana",
    "Root beer": "Root beer",
    "Tomato juice": "Uncommon Juices",
    "Orange": "Orange",
    "Club soda": "Herbs and Spices",
    "Egg": "Egg",
    "Egg yolk": "Egg",
    "Anis": "Herbs and Spices",
    "Espresso": "Coffee",
    "Tabasco sauce": "Herbs and Spices",
    "Lemon peel": "Garnish",
    "Lemon Juice": "Lemon",
    "Tonic water": "Tonic water",
    "Orange Juice": "Orange",
    "Anise": "Herbs and Spices",
    "Sprite": "Lemon-Lime Soda",
    "Ginger ale": "Ginger Soda",
    "Heavy cream": "Cream",
    "Egg white": "Egg",
    "Coffee": "Coffee",
    "Guava juice": "Uncommon Juices",
    "Apricot": "Apricot",
    "Whipped cream": "Cream",
    "Allspice": "Herbs and Spices",
    "Cinnamon": "Herbs and Spices",
    "Passion fruit juice": "Uncommon Juices",
    "Schweppes Russchian": "Tonic Water",
    "Wormwood": "Herbs and Spices",
    "Egg White": "Egg",
    "Kool-Aid": "Fruit Juice",
    "Fruit": "Fruit",
    "Fresh Lime Juice": "Lime",
    "Pineapple": "Pineapple",
    "Licorice root": "Herbs and Spices",
    "Bitter lemon": "Lemon",
    "Fresh Lemon Juice": "Lemon",
    "Nutmeg": "Herbs and Spices",
    "Almond flavoring": "Herbs and Spices",
    "Orange peel": "Garnish",
    "Surge": "Lemon-Lime Soda",
    "Maraschino cherry": "Garnish",
    "Hot chocolate": "Chocolate Milk",
    "Cherry": "Cherry",
    "Lime juice cordial": "Lime",
    "Mint": "Herbs and Spices",
    "Soda Water": "Soda Water",
    "Pineapple juice": "Pineapple juice",
    "Yoghurt": "Yoghurt",
    "Pineapple Juice": "Pineapple Juice",
    "Cranberry juice": "Cranberry juice",
    "Black pepper": "Herbs and Spices",
    "Pepper": "Herbs and Spices",
    "Cardamom": "Herbs and Spices",
    "Lavender": "Herbs and Spices",
    "Chili powder": "Herbs and Spices",
    "Asafoetida": "Herbs and Spices",
    "Cranberries": "Cranberries",
    "Cranberry sauce": "Cranberry sauce",
    "Whipping Cream": "Cream",
    "Vanilla Extract": "Herbs and Spices",
    "Vanilla": "Herbs and Spices",
    "Salt": "Herbs and Spices",
    "Pepsi Cola": "Cola",
    "Peppermint Extract": "Herbs and Spices",
    "Olive": "Garnish",
    "Olive Brine": "Olive Brine",
    "Marjoram Leaves": "Herbs and Spices",
    "Lime Peel": "Garnish",
    "Half-and-half": "Cream",
    "Cloves": "Herbs and Spices",
    "Chocolate Milk": "Chocolate Milk",
    "Chocolate": "Chocolate",
    "Celery Salt": "Herbs and Spices",
    "Cherries": "Garnish",
    "cayenne Pepper": "Herbs and Spices",
    "Caramel Coloring": "Herbs and Spices",
    "Chocolate Sauce": "Chocolate Sauce",
    "Cream": "Cream",
    "Food Coloring": "Herbs and Spices",
    "Cumin Seed": "Herbs and Spices",
    "Oreo Cookies": "Sweets",
    "Candy": "Sweets",
    "Marshmallows": "Sweets",
    "Mini-Snickers Bars": "Sweets",
    "Orange Spiral": "Garnish",
    "sarsaparilla": "Uncommon Soft-Drinks",
    "Tropicana": "Orange Juice",
    "Sherbet": "Sweets",
    "Oreo Cookie": "Sweets",
    "Papaya": "Exotic Fruits",
    "Eggnog": "Egg",
    "Jalapeno juice": "Uncommon juices",
    "Lemon Sorbet": "Sweets",
    "Lemon balm": "Herbs and Spices",
    "Lime soda": "Lemon-Lime Soda",
    "Lime Sorbet": "Sweets",
    "Mint leaves": "Herbs and Spices",
    "Worcestershire sauce": "Herbs and Spices",
    "Zima": "Lemon-Lime Soda",
    "lemon juice": "Lemon",
    "orange juice": "Orange",
    "pineapple juice": "Pineapple juice",
    "Butter": "Dairy",
    "Carbonated soft drink": "Uncommon Soft-Drinks",
    "Carbonated water": "Soda water",
    "Cocoa powder": "Herbs and Spices",
    "Coconut milk": "Coconut Milk",
    "Fresca": "Uncommon Soft-Drinks",
    "Fruit juice": "Fruit Juice",
    "Fruit punch": "Fruit Juice",
    "Vanilla extract": "Herbs and Spices",
    "Saline solution": "Water",
    "Jello": "Sweets",
    "Kiwi": "Kiwi",
    "Daiquiri mix": "Cocktail mix",
    "Dr. Pepper": "Dr. Pepper",
    "Fennel seeds": "Herbs and Spices",
    "Condensed milk": "Condensed Milk",
    "Coriander": "Herbs and Spices",
    "Cornstarch": "Herbs and Spices",
    "Grape juice": "Grape juice",
    "Grapes": "Grapes",
    "Pina colada mix": "Cocktail Mix",
    "Pink lemonade": "Lemonade",
    "Lemon-lime soda": "Lemon-Lime Soda",
    "Limeade": "Lemonade",
    "Mango": "Mango",

    # Liqueurs
    "Blueberry schnapps": "Blueberry Liqueur",
    "Orange Curacao": "Triple Sec",
    "Butterscotch schnapps": "Butterscotch Liqueur",
    "Apfelkorn": "Apple Liqueur",
    "Peach schnapps": "Peach Liqueur",
    "Pisang Ambon": "Banana Liqueur",
    "Creme de Banane": "Banana Liqueur",
    "Banana Liqueur": "Banana Liqueur",
    "Dark Creme de Cacao": "Chocolate Liqueur",
    "Apple schnapps": "Apple Liqueur",
    "Green Creme de Menthe": "Peppermint Liqueur",
    "Galliano": "Vanilla Liqueur",
    "Coconut liqueur": "Coconut Liqueur",
    "Godiva liqueur": "Chocolate Liqueur",
    "Tia maria": "Coffee Liqueur",
    "Erin Cream": "Cream Liqueur",
    "Chambord raspberry liqueur": "Raspberry Liqueur",
    "Rumple Minze": "Peppermint Liqueur",
    "Frangelico": "Nut Liqueur",
    "Strawberry liqueur": "Strawberry Liqueur",
    "Creme de Cassis": "Blackcurrant Liqueur",
    "Cointreau": "Triple Sec",
    "Anisette": "Anise Liqueur",
    "Grain alcohol": "Everclear",
    "Yellow Chartreuse": "Chartreuse",
    "Kummel": "Kummel Liqueur",
    "Benedictine": "Benedictine",
    "Creme de Cacao": "Chocolate Liqueur",
    "Chocolate liqueur": "Chocolate liqueur",
    "Goldschlager": "Cinnamon Liqueur",
    "Blue Curacao": "Triple Sec",
    "Kahlua": "Coffee Liqueur",
    "Amaretto": "Amaretto",
    "Applejack": "Apple Liqueur",
    "White Creme de Menthe": "Peppermint Liqueur",
    "Strawberry schnapps": "Strawberry Liqueur",
    "Peppermint schnapps": "Peppermint Liqueur",
    "Triple sec": "Triple Sec",
    "Campari": "Campari",
    "JÃ¤germeister": "JÃ¤germeister",
    "Bailey's irish cream": "Cream Liqueur",
    "Baileys irish cream": "Cream Liqueur",
    "Everclear": "Everclear",
    "Irish cream": "Cream Liqueur",
    "Coffee liqueur": "Coffee Liqueur",
    "Midori melon liqueur": "Melon Liqueur",
    "Grand Marnier": "Triple Sec",
    "St. Germain": "Elderflower Liqueur",
    "Absinthe": "Strong Spirits",
    "Advocaat": "Egg Liqueur",
    "Aperol": "Aperol",
    "Aquavit": "Aquavit",
    "Cherry Heering": "Cherry Liqueur",
    "Cachaca": "Cachaca Spirit",
    "Curacao": "Triple Sec",
    "Peachtree Schnapps": "Peach Liqueur",
    "Drambuie": "Herbal Liqueur",
    "Fernet-Branca": "Bitter Liqueur",
    "Green Chartreuse": "Chartreuse",
    "Jägermeister": "Jägermeister",
    "Lemoncello": "Limoncello Liqueur",
    "Maraschino liqueur": "Cherry Liqueur",
    "Ouzo": "Anise Liqueur",
    "Pimm's": "Herbal Liqueur",
    "Ricard": "Anise Liqueur",
    "Rosolio": "Floral Liqueur",
    "Triple Sec": "Triple Sec",
    "Cherry liqueur": "Cherry Liqueur",
    "Coffee brandy": "Coffee Liqueur",
    "Raspberry liqueur": "Raspberry Liqueur",
    "Creme de mure": "Blackberry Liqueur",
    "Firewater": "Strong Spirits",
    "Kiwi liqueur": "Kiwi Liqueur",
    "Melon liqueur": "Melon Liqueur",

    # Flavored Brandy
    "Apple brandy": "Flavoured Brandy",
    "Cherry brandy": "Flavored Brandy",
    "Blackberry brandy": "Flavored Brandy",
    "Apricot brandy": "Flavored Brandy",
    "Kirschwasser": "Flavored Brandy",
    "Peach Brandy": "Flavored Brandy",
    "Pisco": "Flavored Brandy",
    "Poire Williams": "Flavoured Brandy",

    # Bitters
    "Bitters": "Bitters",
    "Angostura Bitters": "Bitters",
    "Orange bitters": "Bitters",
    "Chocolate bitters": "Bitters",
    "Peychaud bitters": "Bitters",
    "Peach Bitters": "Bitters",
    "Rhubarb bitters": "Bitters",


    #new



}

SYNONYMS = { raw.strip().lower(): canon for raw, canon in original_data.items() }

def normalize_ingredient(raw: str) -> str:
    """
    Trim/case-normalize raw, then collapse via SYNONYMS.
    Falls back to the lowercased raw.
    """
    key = raw.strip().lower()
    return SYNONYMS.get(key, key)

